name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      sqlite:
        image: sqlite:latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 8.0.0
          bundler-cache: true
          
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          
      - name: Setup database
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
          
      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rails test
        
      - name: Run RuboCop
        run: bundle exec rubocop
        
      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: bundle exec coveralls push
